version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: '05:00'

    open-pull-requests-limit: 5

    commit-message:
      prefix: "chore"

    ignore:
      - dependency-name: "@nestjs/*"
        update-types: ["version-update:semver-major"]